name: nakama
data_dir: /nakama/data

database:
  address:
    - nakama:localdb@postgres:5432/nakama

logger:
  level: DEBUG

socket:
  server_key: defaultkey

session:
  encryption_key: defaultencryptionkey
  refresh_encryption_key: defaultrefreshencryptionkey

runtime:
  http_key: defaulthttpkey
  path: /nakama/data/modules
